name: Scheduled Scraper Update

on:
  schedule:
     - cron: '0 3 * * 0'

  workflow_dispatch:  # Optional: allow manual trigger too

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run scraper
        run: python main.py -H

      - name: Commit and push if data.csv changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Events.csv
          git add Fights.csv
          git diff --cached --quiet || git commit -m "Update CSV via GitHub Actions"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
